In [1]:
import numpy as np 
import pandas as pd

In [2]:
dict1 = {
    "name":['harry','rohan','skillf','vinod'],
    "marks":[92,34,24,67],
    "city":['rampur','kolkata','bareilly','fulera']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks      city
0   harry     92    rampur
1   rohan     34   kolkata
2  skillf     24  bareilly
3   vinod     67    fulera

In [5]:
df.to_csv('raw_data_indexFalse.csv',index=False)

In [6]:
df.head(2)

    name  marks     city
0  harry     92   rampur
1  rohan     34  kolkata

In [7]:
df.tail(2)

     name  marks      city
2  skillf     24  bareilly
3   vinod     67    fulera

In [8]:
df.describe()

           marks
count   4.000000
mean   54.250000
std    31.159536
min    24.000000
25%    31.500000
50%    50.500000
75%    73.250000
max    92.000000

In [9]:
df = pd.read_csv('Ravi_s_data.csv')

In [10]:
df

    name  marks      city
0   ravi     92    rampur
1  bobby     98   kolkata
2    som     56  bareilly

In [11]:
# df['marks'][0] = 78

In [12]:
df

    name  marks      city
0   ravi     92    rampur
1  bobby     98   kolkata
2    som     56  bareilly

In [13]:
df.index = [1,2,3]

In [14]:
df

    name  marks      city
1   ravi     92    rampur
2  bobby     98   kolkata
3    som     56  bareilly

In [15]:
df.index = ['first','second','third']

In [16]:
df

         name  marks      city
first    ravi     92    rampur
second  bobby     98   kolkata
third     som     56  bareilly

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, first to third
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   marks   3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [18]:
ser = pd.Series(np.round(np.random.rand(34)*100))

In [19]:
ser

0     95.0
1     25.0
2     35.0
3     61.0
4      4.0
5     28.0
6     64.0
7     99.0
8     40.0
9     10.0
10    69.0
11    76.0
12    14.0
13    79.0
14    78.0
15    67.0
16    64.0
17    62.0
18    39.0
19     9.0
20    41.0
21    48.0
22    22.0
23    99.0
24    18.0
25    50.0
26    53.0
27    32.0
28     9.0
29    49.0
30    82.0
31    26.0
32    76.0
33    55.0
dtype: float64

In [20]:
type(ser)

pandas.core.series.Series

In [21]:
newdf = pd.DataFrame(np.round(np.random.rand(334,5)*100),index = np.arange(334))

In [22]:
type(newdf)
newdf.head()

      0     1     2     3     4
0  79.0  46.0  95.0  87.0  57.0
1  68.0  73.0  50.0  10.0  84.0
2  84.0  78.0  51.0  27.0  83.0
3  71.0  79.0  11.0  53.0  95.0
4  56.0   2.0  47.0  43.0  36.0

In [23]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean    52.979042   48.311377   51.523952   50.769461   49.131737
std     29.446692   28.113969   28.950268   29.428860   28.919075
min      0.000000    0.000000    0.000000    0.000000    0.000000
25%     29.250000   25.000000   27.250000   25.000000   22.250000
50%     52.500000   46.000000   51.000000   51.000000   48.000000
75%     79.000000   73.000000   75.000000   77.000000   74.000000
max    100.000000  100.000000  100.000000  100.000000  100.000000

In [24]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [25]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [26]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [27]:
newdf.to_numpy()

array([[79., 46., 95., 87., 57.],
       [68., 73., 50., 10., 84.],
       [84., 78., 51., 27., 83.],
       ...,
       [47., 39., 88., 72., 26.],
       [59., 32., 91., 12., 14.],
       [57., 36., 88., 54., 33.]], shape=(334, 5))

In [28]:
newdf.head()

      0     1     2     3     4
0  79.0  46.0  95.0  87.0  57.0
1  68.0  73.0  50.0  10.0  84.0
2  84.0  78.0  51.0  27.0  83.0
3  71.0  79.0  11.0  53.0  95.0
4  56.0   2.0  47.0  43.0  36.0

In [29]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,79.0,68.0,84.0,71.0,56.0,12.0,94.0,30.0,99.0,23.0,...,64.0,7.0,75.0,89.0,99.0,36.0,92.0,47.0,59.0,57.0
1,46.0,73.0,78.0,79.0,2.0,92.0,45.0,32.0,20.0,9.0,...,59.0,2.0,16.0,83.0,15.0,69.0,3.0,39.0,32.0,36.0
2,95.0,50.0,51.0,11.0,47.0,69.0,38.0,21.0,25.0,23.0,...,91.0,85.0,27.0,96.0,60.0,23.0,3.0,88.0,91.0,88.0
3,87.0,10.0,27.0,53.0,43.0,66.0,52.0,18.0,16.0,27.0,...,50.0,18.0,60.0,43.0,99.0,96.0,32.0,72.0,12.0,54.0
4,57.0,84.0,83.0,95.0,36.0,39.0,40.0,5.0,57.0,38.0,...,58.0,53.0,82.0,28.0,54.0,38.0,87.0,26.0,14.0,33.0

In [30]:
newdf.sort_index(axis=0,ascending = False)

        0     1     2     3     4
333  57.0  36.0  88.0  54.0  33.0
332  59.0  32.0  91.0  12.0  14.0
331  47.0  39.0  88.0  72.0  26.0
330  92.0   3.0   3.0  32.0  87.0
329  36.0  69.0  23.0  96.0  38.0
..    ...   ...   ...   ...   ...
4    56.0   2.0  47.0  43.0  36.0
3    71.0  79.0  11.0  53.0  95.0
2    84.0  78.0  51.0  27.0  83.0
1    68.0  73.0  50.0  10.0  84.0
0    79.0  46.0  95.0  87.0  57.0

[334 rows x 5 columns]

In [31]:
newdf.sort_index(axis = 1,ascending=False)

        4     3     2     1     0
0    57.0  87.0  95.0  46.0  79.0
1    84.0  10.0  50.0  73.0  68.0
2    83.0  27.0  51.0  78.0  84.0
3    95.0  53.0  11.0  79.0  71.0
4    36.0  43.0  47.0   2.0  56.0
..    ...   ...   ...   ...   ...
329  38.0  96.0  23.0  69.0  36.0
330  87.0  32.0   3.0   3.0  92.0
331  26.0  72.0  88.0  39.0  47.0
332  14.0  12.0  91.0  32.0  59.0
333  33.0  54.0  88.0  36.0  57.0

[334 rows x 5 columns]

In [32]:
newdf2 = newdf

In [33]:
newdf2[0][0] = 99

C:\Users\HP\AppData\Local\Temp\ipykernel_9356\3918156449.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 99

In [34]:
newdf

        0     1     2     3     4
0    99.0  46.0  95.0  87.0  57.0
1    68.0  73.0  50.0  10.0  84.0
2    84.0  78.0  51.0  27.0  83.0
3    71.0  79.0  11.0  53.0  95.0
4    56.0   2.0  47.0  43.0  36.0
..    ...   ...   ...   ...   ...
329  36.0  69.0  23.0  96.0  38.0
330  92.0   3.0   3.0  32.0  87.0
331  47.0  39.0  88.0  72.0  26.0
332  59.0  32.0  91.0  12.0  14.0
333  57.0  36.0  88.0  54.0  33.0

[334 rows x 5 columns]

In [35]:
newdf2 = newdf.copy()

In [36]:
newdf2[0][0] = 45

C:\Users\HP\AppData\Local\Temp\ipykernel_9356\2561628386.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 45

In [37]:
newdf

        0     1     2     3     4
0    99.0  46.0  95.0  87.0  57.0
1    68.0  73.0  50.0  10.0  84.0
2    84.0  78.0  51.0  27.0  83.0
3    71.0  79.0  11.0  53.0  95.0
4    56.0   2.0  47.0  43.0  36.0
..    ...   ...   ...   ...   ...
329  36.0  69.0  23.0  96.0  38.0
330  92.0   3.0   3.0  32.0  87.0
331  47.0  39.0  88.0  72.0  26.0
332  59.0  32.0  91.0  12.0  14.0
333  57.0  36.0  88.0  54.0  33.0

[334 rows x 5 columns]

In [38]:
newdf2

        0     1     2     3     4
0    45.0  46.0  95.0  87.0  57.0
1    68.0  73.0  50.0  10.0  84.0
2    84.0  78.0  51.0  27.0  83.0
3    71.0  79.0  11.0  53.0  95.0
4    56.0   2.0  47.0  43.0  36.0
..    ...   ...   ...   ...   ...
329  36.0  69.0  23.0  96.0  38.0
330  92.0   3.0   3.0  32.0  87.0
331  47.0  39.0  88.0  72.0  26.0
332  59.0  32.0  91.0  12.0  14.0
333  57.0  36.0  88.0  54.0  33.0

[334 rows x 5 columns]

In [39]:
newdf.loc[0,0] = 654

In [40]:
newdf.head()

       0     1     2     3     4
0  654.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0
2   84.0  78.0  51.0  27.0  83.0
3   71.0  79.0  11.0  53.0  95.0
4   56.0   2.0  47.0  43.0  36.0

In [41]:
newdf.columns = list("ABCDE")

In [42]:
newdf.head(2)

       A     B     C     D     E
0  654.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0

In [43]:
newdf.loc[0,'A'] = 650

In [44]:
newdf.head(2)

       A     B     C     D     E
0  650.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0

In [45]:
newdf.loc[0,0] = 67

In [46]:
newdf

         A     B     C     D     E     0
0    650.0  46.0  95.0  87.0  57.0  67.0
1     68.0  73.0  50.0  10.0  84.0   NaN
2     84.0  78.0  51.0  27.0  83.0   NaN
3     71.0  79.0  11.0  53.0  95.0   NaN
4     56.0   2.0  47.0  43.0  36.0   NaN
..     ...   ...   ...   ...   ...   ...
329   36.0  69.0  23.0  96.0  38.0   NaN
330   92.0   3.0   3.0  32.0  87.0   NaN
331   47.0  39.0  88.0  72.0  26.0   NaN
332   59.0  32.0  91.0  12.0  14.0   NaN
333   57.0  36.0  88.0  54.0  33.0   NaN

[334 rows x 6 columns]

In [47]:
newdf = newdf.drop(0,axis = 1)

In [48]:
newdf.head(10)

       A     B     C     D     E
0  650.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0
2   84.0  78.0  51.0  27.0  83.0
3   71.0  79.0  11.0  53.0  95.0
4   56.0   2.0  47.0  43.0  36.0
5   12.0  92.0  69.0  66.0  39.0
6   94.0  45.0  38.0  52.0  40.0
7   30.0  32.0  21.0  18.0   5.0
8   99.0  20.0  25.0  16.0  57.0
9   23.0   9.0  23.0  27.0  38.0

In [49]:
newdf.loc[[1,2],['C','D']]

      C     D
1  50.0  10.0
2  51.0  27.0

In [50]:
newdf.head()

       A     B     C     D     E
0  650.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0
2   84.0  78.0  51.0  27.0  83.0
3   71.0  79.0  11.0  53.0  95.0
4   56.0   2.0  47.0  43.0  36.0

In [51]:
newdf.loc[(newdf['A']<3)&(newdf['B']>1)]

       A     B     C     D     E
10   0.0  72.0   8.0  97.0  56.0
11   2.0  26.0  28.0  20.0  19.0
115  2.0  22.0  18.0  11.0  59.0
145  2.0   7.0  33.0  80.0  46.0
215  2.0  76.0  42.0  39.0  75.0
246  1.0  26.0  54.0  90.0  59.0
290  0.0  14.0  16.0  27.0  24.0
293  2.0   9.0  83.0  85.0   6.0
310  1.0  67.0  99.0  25.0  31.0

In [52]:
newdf.head(2)

       A     B     C     D     E
0  650.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0

In [53]:
newdf.iloc[0,4]

np.float64(57.0)

In [54]:
newdf.iloc[[0,1],[1,2]]

      B     C
0  46.0  95.0
1  73.0  50.0

In [55]:
newdf.head(3)

       A     B     C     D     E
0  650.0  46.0  95.0  87.0  57.0
1   68.0  73.0  50.0  10.0  84.0
2   84.0  78.0  51.0  27.0  83.0

In [56]:
newdf.drop([0])

        A     B     C     D     E
1    68.0  73.0  50.0  10.0  84.0
2    84.0  78.0  51.0  27.0  83.0
3    71.0  79.0  11.0  53.0  95.0
4    56.0   2.0  47.0  43.0  36.0
5    12.0  92.0  69.0  66.0  39.0
..    ...   ...   ...   ...   ...
329  36.0  69.0  23.0  96.0  38.0
330  92.0   3.0   3.0  32.0  87.0
331  47.0  39.0  88.0  72.0  26.0
332  59.0  32.0  91.0  12.0  14.0
333  57.0  36.0  88.0  54.0  33.0

[333 rows x 5 columns]

In [57]:
newdf

         A     B     C     D     E
0    650.0  46.0  95.0  87.0  57.0
1     68.0  73.0  50.0  10.0  84.0
2     84.0  78.0  51.0  27.0  83.0
3     71.0  79.0  11.0  53.0  95.0
4     56.0   2.0  47.0  43.0  36.0
..     ...   ...   ...   ...   ...
329   36.0  69.0  23.0  96.0  38.0
330   92.0   3.0   3.0  32.0  87.0
331   47.0  39.0  88.0  72.0  26.0
332   59.0  32.0  91.0  12.0  14.0
333   57.0  36.0  88.0  54.0  33.0

[334 rows x 5 columns]

In [58]:
newdf.drop(['A','B'],axis=1,inplace=True)

In [59]:
newdf

        C     D     E
0    95.0  87.0  57.0
1    50.0  10.0  84.0
2    51.0  27.0  83.0
3    11.0  53.0  95.0
4    47.0  43.0  36.0
..    ...   ...   ...
329  23.0  96.0  38.0
330   3.0  32.0  87.0
331  88.0  72.0  26.0
332  91.0  12.0  14.0
333  88.0  54.0  33.0

[334 rows x 3 columns]

In [60]:
newdf.drop([0,5],axis=0,inplace=True)

In [61]:
newdf

        C     D     E
1    50.0  10.0  84.0
2    51.0  27.0  83.0
3    11.0  53.0  95.0
4    47.0  43.0  36.0
6    38.0  52.0  40.0
..    ...   ...   ...
329  23.0  96.0  38.0
330   3.0  32.0  87.0
331  88.0  72.0  26.0
332  91.0  12.0  14.0
333  88.0  54.0  33.0

[332 rows x 3 columns]

In [62]:
newdf.head(3)

      C     D     E
1  50.0  10.0  84.0
2  51.0  27.0  83.0
3  11.0  53.0  95.0

In [63]:
newdf.reset_index()

     index     C     D     E
0        1  50.0  10.0  84.0
1        2  51.0  27.0  83.0
2        3  11.0  53.0  95.0
3        4  47.0  43.0  36.0
4        6  38.0  52.0  40.0
..     ...   ...   ...   ...
327    329  23.0  96.0  38.0
328    330   3.0  32.0  87.0
329    331  88.0  72.0  26.0
330    332  91.0  12.0  14.0
331    333  88.0  54.0  33.0

[332 rows x 4 columns]

In [64]:
newdf

        C     D     E
1    50.0  10.0  84.0
2    51.0  27.0  83.0
3    11.0  53.0  95.0
4    47.0  43.0  36.0
6    38.0  52.0  40.0
..    ...   ...   ...
329  23.0  96.0  38.0
330   3.0  32.0  87.0
331  88.0  72.0  26.0
332  91.0  12.0  14.0
333  88.0  54.0  33.0

[332 rows x 3 columns]

In [65]:
newdf.reset_index(inplace=True,drop=True)

In [66]:
newdf

        C     D     E
0    50.0  10.0  84.0
1    51.0  27.0  83.0
2    11.0  53.0  95.0
3    47.0  43.0  36.0
4    38.0  52.0  40.0
..    ...   ...   ...
327  23.0  96.0  38.0
328   3.0  32.0  87.0
329  88.0  72.0  26.0
330  91.0  12.0  14.0
331  88.0  54.0  33.0

[332 rows x 3 columns]

In [67]:
newdf['C'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
327    False
328    False
329    False
330    False
331    False
Name: C, Length: 332, dtype: bool

In [68]:
df = pd.DataFrame(
    {
        "name": ["Alfred", "Batman", "Alfred"],
        "toy": [np.nan, "Batmobile", "Bullwhip"],
        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    }
)

In [69]:
df

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [70]:
df.dropna(how='all')

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [71]:
df.drop_duplicates(subset=['name'],keep='last')

     name        toy       born
1  Batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [72]:
df.shape

(3, 3)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [74]:
df['name'].value_counts(dropna=False)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [75]:
data = pd.read_excel('')

FileNotFoundError: [Errno 2] No such file or directory: ''